@echo off
echo Cleaning node_modules...
rmdir /s /q node_modules
echo Cleaning .next folder...
rmdir /s /q .next
echo Cleaning npm cache...
npm cache clean --force
echo Reinstalling dependencies...
npm install
echo Done!
